### ISSUE TITLE
Markdown Filters (Explained)

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles-kb#6]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

``` yaml
title: Markdown Filters (Explained)
categories: tutorials
tags: 
author: raamdev
github-issue: https://github.com/websharks/wp-kb-articles-kb/issues/6
```

---

![md-the_content](https://cloud.githubusercontent.com/assets/1563559/6202440/84d7d0e6-b497-11e4-9745-b0cc160086bd.png)

Also referencing: https://github.com/websharks/wp-kb-articles/issues/67
