### ISSUE TITLE
What happens when a KB Article is synced with GitHub?

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles-kb#9]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs
- [ ] Once this is published live, update the Target URL on the Redirect on wpkbarticles.com to use the published link: https://wpkbarticles.com/wp-admin/post.php?post=39&action=edit (the redirect URL is used inside plugin dashboard messages; see websharks/wp-kb-articles#51)

``` yaml
title: What happens when a KB Article is synced with GitHub?
categories: questions
tags: github-integration
author: raamdev
github-issue: https://github.com/websharks/wp-kb-articles-kb/issues/9
```

---

[needs to be drafted]
